package com.readymix.model;
// Generated Sep 4, 2017 3:53:01 PM by Hibernate Tools 4.3.1



/**
 * ChBillOfSupply generated by hbm2java
 */
public class ChBillOfSupply  implements java.io.Serializable {


     private Integer srNo;
     private PrBillOfSupply prBillOfSupply;
     private String productDesc;
     private String hsnCode;
     private Integer qty;
     private Float beforeTax;
     private Float afterTax;
     private Float amt;
     private Float valueOfSupply;
     private Float chTotal;

    public ChBillOfSupply() {
    }

	
    public ChBillOfSupply(PrBillOfSupply prBillOfSupply) {
        this.prBillOfSupply = prBillOfSupply;
    }
    public ChBillOfSupply(PrBillOfSupply prBillOfSupply, String productDesc, String hsnCode, Integer qty, Float beforeTax, Float afterTax, Float amt, Float valueOfSupply, Float chTotal) {
       this.prBillOfSupply = prBillOfSupply;
       this.productDesc = productDesc;
       this.hsnCode = hsnCode;
       this.qty = qty;
       this.beforeTax = beforeTax;
       this.afterTax = afterTax;
       this.amt = amt;
       this.valueOfSupply = valueOfSupply;
       this.chTotal = chTotal;
    }
   
    public Integer getSrNo() {
        return this.srNo;
    }
    
    public void setSrNo(Integer srNo) {
        this.srNo = srNo;
    }
    public PrBillOfSupply getPrBillOfSupply() {
        return this.prBillOfSupply;
    }
    
    public void setPrBillOfSupply(PrBillOfSupply prBillOfSupply) {
        this.prBillOfSupply = prBillOfSupply;
    }
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }
    public String getHsnCode() {
        return this.hsnCode;
    }
    
    public void setHsnCode(String hsnCode) {
        this.hsnCode = hsnCode;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Float getBeforeTax() {
        return this.beforeTax;
    }
    
    public void setBeforeTax(Float beforeTax) {
        this.beforeTax = beforeTax;
    }
    public Float getAfterTax() {
        return this.afterTax;
    }
    
    public void setAfterTax(Float afterTax) {
        this.afterTax = afterTax;
    }
    public Float getAmt() {
        return this.amt;
    }
    
    public void setAmt(Float amt) {
        this.amt = amt;
    }
    public Float getValueOfSupply() {
        return this.valueOfSupply;
    }
    
    public void setValueOfSupply(Float valueOfSupply) {
        this.valueOfSupply = valueOfSupply;
    }
    public Float getChTotal() {
        return this.chTotal;
    }
    
    public void setChTotal(Float chTotal) {
        this.chTotal = chTotal;
    }




}


