package com.readymix.model;
// Generated Sep 4, 2017 3:53:01 PM by Hibernate Tools 4.3.1



/**
 * ChReceiptVoucher generated by hbm2java
 */
public class ChReceiptVoucher  implements java.io.Serializable {


     private Integer receiptNo;
     private PrReceiptVoucher prReceiptVoucher;
     private String productDesc;
     private String hsnCode;
     private Float beforeTax;
     private Float afterTax;
     private Float taxableValue;
     private Float cgRate;
     private Float cgAmt;
     private Float sgRate;
     private Float sgAmt;
     private Float chTotal;

    public ChReceiptVoucher() {
    }

	
    public ChReceiptVoucher(PrReceiptVoucher prReceiptVoucher) {
        this.prReceiptVoucher = prReceiptVoucher;
    }
    public ChReceiptVoucher(PrReceiptVoucher prReceiptVoucher, String productDesc, String hsnCode, Float beforeTax, Float afterTax, Float taxableValue, Float cgRate, Float cgAmt, Float sgRate, Float sgAmt, Float chTotal) {
       this.prReceiptVoucher = prReceiptVoucher;
       this.productDesc = productDesc;
       this.hsnCode = hsnCode;
       this.beforeTax = beforeTax;
       this.afterTax = afterTax;
       this.taxableValue = taxableValue;
       this.cgRate = cgRate;
       this.cgAmt = cgAmt;
       this.sgRate = sgRate;
       this.sgAmt = sgAmt;
       this.chTotal = chTotal;
    }
   
    public Integer getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(Integer receiptNo) {
        this.receiptNo = receiptNo;
    }
    public PrReceiptVoucher getPrReceiptVoucher() {
        return this.prReceiptVoucher;
    }
    
    public void setPrReceiptVoucher(PrReceiptVoucher prReceiptVoucher) {
        this.prReceiptVoucher = prReceiptVoucher;
    }
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }
    public String getHsnCode() {
        return this.hsnCode;
    }
    
    public void setHsnCode(String hsnCode) {
        this.hsnCode = hsnCode;
    }
    public Float getBeforeTax() {
        return this.beforeTax;
    }
    
    public void setBeforeTax(Float beforeTax) {
        this.beforeTax = beforeTax;
    }
    public Float getAfterTax() {
        return this.afterTax;
    }
    
    public void setAfterTax(Float afterTax) {
        this.afterTax = afterTax;
    }
    public Float getTaxableValue() {
        return this.taxableValue;
    }
    
    public void setTaxableValue(Float taxableValue) {
        this.taxableValue = taxableValue;
    }
    public Float getCgRate() {
        return this.cgRate;
    }
    
    public void setCgRate(Float cgRate) {
        this.cgRate = cgRate;
    }
    public Float getCgAmt() {
        return this.cgAmt;
    }
    
    public void setCgAmt(Float cgAmt) {
        this.cgAmt = cgAmt;
    }
    public Float getSgRate() {
        return this.sgRate;
    }
    
    public void setSgRate(Float sgRate) {
        this.sgRate = sgRate;
    }
    public Float getSgAmt() {
        return this.sgAmt;
    }
    
    public void setSgAmt(Float sgAmt) {
        this.sgAmt = sgAmt;
    }
    public Float getChTotal() {
        return this.chTotal;
    }
    
    public void setChTotal(Float chTotal) {
        this.chTotal = chTotal;
    }




}


