package com.readymix.model;
// Generated Sep 4, 2017 3:53:01 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer lid;
     private String fullName;
     private String designation;
     private String mobileNo;
     private String LType;
     private String loginId;
     private String password;
     private String email;

    public Login() {
    }

    public Login(String fullName, String designation, String mobileNo, String LType, String loginId, String password, String email) {
       this.fullName = fullName;
       this.designation = designation;
       this.mobileNo = mobileNo;
       this.LType = LType;
       this.loginId = loginId;
       this.password = password;
       this.email = email;
    }
   
    public Integer getLid() {
        return this.lid;
    }
    
    public void setLid(Integer lid) {
        this.lid = lid;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getLType() {
        return this.LType;
    }
    
    public void setLType(String LType) {
        this.LType = LType;
    }
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


