package com.readymix.model;
// Generated Sep 4, 2017 3:53:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrBillOfSupply generated by hbm2java
 */
public class PrBillOfSupply  implements java.io.Serializable {


     private Integer billD;
     private Integer invoiceNo;
     private Date dateOfIssue;
     private String state;
     private String stateCode;
     private String billToName;
     private String billToAddress;
     private String billToGstinUin;
     private String billToState;
     private String billToCode;
     private String shipToName;
     private String shipToAddress;
     private String shipToGstin;
     private String shipToState;
     private String shipToCode;
     private Float prTotal;
     private String totalInWords;
     private String bankAc;
     private String bankIfsc;
     private String authrizedSignatory;
     private String termsCond;
     private Set chBillOfSupplies = new HashSet(0);

    public PrBillOfSupply() {
    }

    public PrBillOfSupply(Integer invoiceNo, Date dateOfIssue, String state, String stateCode, String billToName, String billToAddress, String billToGstinUin, String billToState, String billToCode, String shipToName, String shipToAddress, String shipToGstin, String shipToState, String shipToCode, Float prTotal, String totalInWords, String bankAc, String bankIfsc, String authrizedSignatory, String termsCond, Set chBillOfSupplies) {
       this.invoiceNo = invoiceNo;
       this.dateOfIssue = dateOfIssue;
       this.state = state;
       this.stateCode = stateCode;
       this.billToName = billToName;
       this.billToAddress = billToAddress;
       this.billToGstinUin = billToGstinUin;
       this.billToState = billToState;
       this.billToCode = billToCode;
       this.shipToName = shipToName;
       this.shipToAddress = shipToAddress;
       this.shipToGstin = shipToGstin;
       this.shipToState = shipToState;
       this.shipToCode = shipToCode;
       this.prTotal = prTotal;
       this.totalInWords = totalInWords;
       this.bankAc = bankAc;
       this.bankIfsc = bankIfsc;
       this.authrizedSignatory = authrizedSignatory;
       this.termsCond = termsCond;
       this.chBillOfSupplies = chBillOfSupplies;
    }
   
    public Integer getBillD() {
        return this.billD;
    }
    
    public void setBillD(Integer billD) {
        this.billD = billD;
    }
    public Integer getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(Integer invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public Date getDateOfIssue() {
        return this.dateOfIssue;
    }
    
    public void setDateOfIssue(Date dateOfIssue) {
        this.dateOfIssue = dateOfIssue;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    public String getBillToName() {
        return this.billToName;
    }
    
    public void setBillToName(String billToName) {
        this.billToName = billToName;
    }
    public String getBillToAddress() {
        return this.billToAddress;
    }
    
    public void setBillToAddress(String billToAddress) {
        this.billToAddress = billToAddress;
    }
    public String getBillToGstinUin() {
        return this.billToGstinUin;
    }
    
    public void setBillToGstinUin(String billToGstinUin) {
        this.billToGstinUin = billToGstinUin;
    }
    public String getBillToState() {
        return this.billToState;
    }
    
    public void setBillToState(String billToState) {
        this.billToState = billToState;
    }
    public String getBillToCode() {
        return this.billToCode;
    }
    
    public void setBillToCode(String billToCode) {
        this.billToCode = billToCode;
    }
    public String getShipToName() {
        return this.shipToName;
    }
    
    public void setShipToName(String shipToName) {
        this.shipToName = shipToName;
    }
    public String getShipToAddress() {
        return this.shipToAddress;
    }
    
    public void setShipToAddress(String shipToAddress) {
        this.shipToAddress = shipToAddress;
    }
    public String getShipToGstin() {
        return this.shipToGstin;
    }
    
    public void setShipToGstin(String shipToGstin) {
        this.shipToGstin = shipToGstin;
    }
    public String getShipToState() {
        return this.shipToState;
    }
    
    public void setShipToState(String shipToState) {
        this.shipToState = shipToState;
    }
    public String getShipToCode() {
        return this.shipToCode;
    }
    
    public void setShipToCode(String shipToCode) {
        this.shipToCode = shipToCode;
    }
    public Float getPrTotal() {
        return this.prTotal;
    }
    
    public void setPrTotal(Float prTotal) {
        this.prTotal = prTotal;
    }
    public String getTotalInWords() {
        return this.totalInWords;
    }
    
    public void setTotalInWords(String totalInWords) {
        this.totalInWords = totalInWords;
    }
    public String getBankAc() {
        return this.bankAc;
    }
    
    public void setBankAc(String bankAc) {
        this.bankAc = bankAc;
    }
    public String getBankIfsc() {
        return this.bankIfsc;
    }
    
    public void setBankIfsc(String bankIfsc) {
        this.bankIfsc = bankIfsc;
    }
    public String getAuthrizedSignatory() {
        return this.authrizedSignatory;
    }
    
    public void setAuthrizedSignatory(String authrizedSignatory) {
        this.authrizedSignatory = authrizedSignatory;
    }
    public String getTermsCond() {
        return this.termsCond;
    }
    
    public void setTermsCond(String termsCond) {
        this.termsCond = termsCond;
    }
    public Set getChBillOfSupplies() {
        return this.chBillOfSupplies;
    }
    
    public void setChBillOfSupplies(Set chBillOfSupplies) {
        this.chBillOfSupplies = chBillOfSupplies;
    }




}


